name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: dart analyze

      - name: Run tests
        run: dart test

  push-code:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
